### ISSUE TITLE
CreateReview.js의 component 이름

### ISSUE THREAD

**Issue by Peace-Song** [swsnu/swpp2019-team14#12]
/review/create로 history push했는데, 404가 뜨길래 봤더니 CreateReview.js에 component 이름이 BookDetail로 되어있네용.. 

`class BookDetail extends Component {
`
이 부분이랑
`export default connect(mapStateToProps, mapDispatchToProps)(BookDetail);
`
이 부분이요!

**Comment by mustardlove** [comment]
맞아요 그부분 저도 발견해서 지금 있는 branch에서는 이름을 고쳤는데 master에는 아직 안 들어가있네요 ㅠㅠ 이따 밤에 고치겠습니다
