### ISSUE TITLE
라이브러리에 추가하기 - 모달 오류

### ISSUE THREAD

**Issue by kanghc0217** [swsnu/swpp2019-team14#176]
![image](https://user-images.githubusercontent.com/40143716/70227637-45b14480-1796-11ea-9095-bbcfae70cc48.png)

라이브러리에 추가하기 버튼을 누르니까
뭔가 모달이 뜨기는 뜨는데
이상한게 뜹니다!

![image](https://user-images.githubusercontent.com/40143716/70227681-5792e780-1796-11ea-9bbf-cbedb91feaf3.png)

**Comment by Peace-Song** [comment]
아직 추가된 라이브러리가 없어서 그래요! 관련된 Ui 추가하겠습니다
