### ISSUE TITLE
User 검색 결과 관련

### ISSUE THREAD

**Issue by kdh9949** [swsnu/swpp2019-team14#178]
검색 결과에서 보이는 팔로워/팔로잉 수가
실제 팔로워/팔로잉 수와 다른 것 같습니다.

(검색결과)
![image](https://user-images.githubusercontent.com/17994874/70227595-35996500-1796-11ea-949b-92721dadb44a.png)

(클릭해서 들어가면 보이는거)
![image](https://user-images.githubusercontent.com/17994874/70227634-45b14480-1796-11ea-96ee-b2b8d0794270.png)

**Comment by Peace-Song** [comment]
네 전자는 아직 로직 연결 안햇어요 ㅠㅠ 후자가 맞습니다
