### ISSUE TITLE
Short review

### ISSUE THREAD

**Issue by mike0295** [swsnu/swpp2019-team14#181]
short review 글자 제한이 현재 글자수 넘을시 ...으로 대체되는데, 작성할때부터 제한을 두는게 나을 것 같습니다!
<img width="861" alt="Screen Shot 2019-12-05 at 7 35 55 PM" src="https://user-images.githubusercontent.com/48646713/70227872-ac366280-1796-11ea-8c95-801a2644d43f.png">

**Comment by Peace-Song** [comment]
넵 반영하겠습니다!
