### ISSUE TITLE
책 정보 받아올 때 Contents 길이가 잘리는 현상

### ISSUE THREAD

**Issue by ybzzang** [swsnu/swpp2019-team14#20]
해리포터 책의 경우

'선과 악의 대립 속에서 평범한 어린 소년이 한 사람의 영웅으로 성장해나가는 보편적인 테마를 바탕으로 빈틈없는 소설적 구성과 생생하게 살아 있는 캐릭터, 정교하게 만들어낸 환상의 세계를 접목시킨 21세기의 고전 「해리포터 시리즈」의 제5편『해리포터와 불사조 기사단』 제1부. 사사건건 해리를 괴롭히는 사촌 두들리와 다투다 디멘터의 습격을 받은 해리는 우여곡절 끝에 친구 론과 헤르미온느가 있는 불사조 기사단의 비밀 본부로 가게 된다. 볼드모트에 대항하는'

까지만 contents로서 받아와지던데 api에서 잘린 채로 주는 건가요?

**Comment by zlzlqlzl** [comment]
네 맞아요 글자수 제한있는거 같더라고요 전체를 보려면 상세url에서 내용 긁어와야 할 것 같긴한데 html받아오는게 막혀있는거같아서 다른방법을 찾아봐야할 것 같아요
