### ISSUE TITLE
model의 field들 길이 제한 

### ISSUE THREAD

**Issue by ybzzang** [swsnu/swpp2019-team14#21]
title, content 등의 field들이 현재 길이 제한이 없는데, 상의를 통해 길이 제한에 대해 이야기해야 할 것 같습니다.

**Comment by mustardlove** [comment]
넵
그리구 백엔드에도  maxlength?? 이런 걸로 걸어놓긴 하겠지만, 우선 프론트엔드에서부터 제한 거는 방향으로 가는 게 좋을 것 같아요
