### ISSUE TITLE
라이브러리 추가시 오류

### ISSUE THREAD

**Issue by zlzlqlzl** [swsnu/swpp2019-team14#216]
책 정보 > 라이브러리에 추가> 라이브러리 만들기 > 닫기 차례로 클릭하거나
라이브러리 만들기에서 책을 추가하려고 누르면 화면이 안 뜨는 버그 입니다.

**Comment by mustardlove** [comment]
책 정보 > 라이브러리에 추가 > 저장    을 하면 화면이 안 뜨는 버그가 있습니다

**Comment by Peace-Song** [comment]
마찬가지로 currentBook으로 넘어가야 할 것이 selectedBook으로 넘어가서 생기는 버그로 판명
