### ISSUE TITLE
라이브러리 모달 오류

### ISSUE THREAD

**Issue by mustardlove** [swsnu/swpp2019-team14#225]
라이브러리 모달에서 책 검색해서 책을 고르면 북디테일로 리다이렉트 돼요

아직 깃풀 안해서 생기는 버그일지도..

**Comment by Peace-Song** [comment]
currentBook으로 들어가야 할 게 언제부터인가 selectedBook으로 바뀌어서 생기는 현상으로 판명. 고쳤습니다
